/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")
    id("scabbard.gradle") version "0.5.0"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

dependencies {
    annotationProcessor("com.google.dagger:dagger-compiler:2.32")
    annotationProcessor("javax.annotation:javax.annotation-api:1.3.2")
    implementation("com.google.dagger:dagger:2.32")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    mainClass.set("sysui_di.App")
}

val run: JavaExec by tasks
run.standardInput = System.`in`

scabbard {
    enabled = true
    fullBindingGraphValidation = true // default false
    failOnError = true
    qualifiedNames = true
    outputFormat = "svg"
}

configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "com.github.kittinunf.result" && requested.name == "result" && requested.version == "3.0.0") {
            useVersion("3.0.1")
            because("Transitive dependency of Scabbard, currently not available on mavenCentral()")
        }
    }
}