/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mockable;

import java.io.File;
import java.io.IOException;

public class App {
    

    public static void main(String[] args) {
    }
}
