/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sysui_di;

import sysui_di.dagger.DaggerReferenceGlobalRootComponent;
import sysui_di.dagger.GlobalRootComponent;

public class App {
    public static void main(String[] args) {
        GlobalRootComponent.Builder builder = DaggerReferenceGlobalRootComponent.builder();
    }
}
