/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mockable;

import java.io.File;
import java.io.IOException;

public class App {
    

    public static void main(String[] args) {
        MockableJarGenerator gen = new MockableJarGenerator(false);
        try {
            gen.createMockableJar(new File("./test-activity.jar"), new File("./android-mock.jar"));
        } catch (IOException e) {
            System.err.println("ioexception " + e.getMessage());
        }
    }
}
